### ISSUE TITLE
我想加入一些go tool

### ISSUE THREAD

**Issue by tossp** [caixw/gobuild#3]
你好，
我想编译之前加入goimports和golint，可以pr过来吗？

最好，非常感谢您为gobuild做的工作

**Comment by caixw** [comment]
我觉得gobuild还是坚持只做热编译的工作，goimports和golint应该属于编译前的检测工作，所以我不是很建议加到gobuild中来。

也谢谢您提的建议！

**Comment by caixw** [comment]
若有其它好的建议，也欢迎PR！
