### ISSUE TITLE
go get 命令下载安装之后，没有在gopath的bin路径下生成gobuild.exe

### ISSUE THREAD

**Issue by RowgerGo** [caixw/gobuild#7]
所以在控制台运行gobuild命令会提示找不到

**Comment by caixw** [comment]
命令行工具在  cmd 之下，而不是根目录下，会不会是这个原因？

**Comment by jiuweidao** [comment]
解决了么？我也有相同的问题

**Comment by caixw** [comment]
在源目录下 cmd 之下，运行 go build 或是 go install 就有了。

**Comment by lijunyong** [comment]
我也是，go get指定版本不会安装

**Comment by caixw** [comment]
go get 没用，因为 main 包不在项目根目录。如果需要手动安装，可以按照以下方式：
```shell
git clone https://github.com/caixw/gobuild.git
cd gobuild/cmd/gobuild
go install
```
或者主流平台可以直接从 <https://github.com/caixw/gobuild/releases> 下载。

**Comment by lijunyong** [comment]
谢谢，搞定了
